import Head from "next/head";
import Canvas from "../components/Canvas";
import Navbar from "../components/Navbar";
import AboutSection from "../components/AboutSection";
import Footer from "../components/Footer";

export default function About() {
  return (
    <div className="page">
      <Head>
        <title>Raiona || About us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <Canvas />
      <Navbar />
      <center style={{ marginBottom: "100px" }}>
        <h1>
          About <span style={{ color: "#cca354" }}>Raiona </span>
        </h1>
      </center>
      <AboutSection />
      <Footer />
    </div>
  );
}
