import Head from "next/head";
import Canvas from "../components/Canvas";
import Navbar from "../components/Navbar";
import ContactForm from "../components/ContactForm";
import Footer from "../components/Footer";

export default function Contact() {
  return (
    <div className="page">
      <Head>
        <title>Raiona || Contact</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <Canvas />
      <Navbar />
      <PageHead />
      <ContactForm />
      <Footer />
    </div>
  );
}

function PageHead() {
  return (
    <center style={{ padding: "0 69px" }}>
      <h2 style={{ fontSize: "50px" }}>
        Welcome to <span style={{ color: "#cca354" }}>Raiona</span>
      </h2>
      <p>
        Raiona is currently in beta testing register now and we will contact you
        as soon as we are ready to launch.
      </p>
    </center>
  );
}
