import Head from "next/head";
import Canvas from "../components/Canvas";
import Navbar from "../components/Navbar";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import TeamsSection from "../components/TeamsSection";
import ContactForm from "../components/ContactForm";
import AboutSection from "../components/AboutSection";

import AboutSwiper from "../components/AboutSwiper";
import CoinsBanner from "../components/CoinsBanner";

export default function Home() {
  return (
    <div className="page">
      <Head>
        <title>Raiona || Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>

      <Canvas />
      <Navbar style={{ position: "fixed" }} />
      <Banner />

      <AboutSwiper />
      <CoinsBanner />

      <AboutSection />
      <TeamsSection />

      <ContactHead />
      <ContactForm />
      <Footer />
    </div>
  );
}

function ContactHead() {
  return (
    <center>
      <h2 style={{ fontSize: "40px" }}>
        Sign up to&nbsp;
        <span style={{ color: "#cca354" }}>Raiona</span>
      </h2>
      <p style={{ fontSize: "12px" }}>
        Raiona is currently in beta testing register now and we will contact you
        as soon as we are ready to launch.
      </p>
    </center>
  );
}
